---
- name: Deploy nmap
  hosts: myhosts

  tasks:
  - name: Install nmap 
    ansible.builtin.apt:
      name: nmap
      state: latest
      update_cache: yes

  - name: Copy index
    ansible.builtin.copy:
      src: ./index.html
      dest: /var/www/html/index.nginx-debian.html
      owner: root
      group: root
      mode: '0666'
