FROM nginx

ADD ./index.html /var/www/html/index.html
ADD ./nginx-conf/nginx.conf /etc/nginx/conf.d/default.conf
ADD ./ssl /etc/nginx/ssl

EXPOSE 80 443

RUN /usr/sbin/nginx -t

STOPSIGNAL SIGTERM

CMD [ "nginx", "-g", "daemon off;" ]